---
stages:
  - lint
  - build
  - package

build_test:
  image: registry.0xacab.org/jkito/bitmask-vpn:latest
  stage: build
  script:
    - make test
    - patch -p1 < docker/*.patch
    # TODO missing xcb package in the docker image. investigate what to install to run minimal tests.
    # - make test_ui
    - PROVIDER=bitmask && make vendor && make build
  tags:
    - linux
  artifacts:
    paths:
      - 'build/qt/release'
    expire_in: 1 week

lint:
  image: golangci/golangci-lint:v1.59-alpine
  stage: build
  script:
    - golangci-lint run --timeout=5m
  tags:
    - linux

debian:
  image: registry.0xacab.org/jkito/bitmask-vpn:latest
  stage: package
  tags:
    - linux
  script:
    - 'PROVIDER="bitmask" make vendor && make package_deb'
  artifacts:
    paths:
      - 'deploy/*.deb'
    expire_in: 1 week

arch:
  image: archlinux
  stage: package
  before_script:
    - "pacman -Suy base-devel --noconfirm"
    - "useradd non_root"
    - "echo 'non_root ALL=NOPASSWD: ALL' >> /etc/sudoers"
    - "mkdir /home/non_root"
    - "cp -r Makefile ArchLinux/ /home/non_root"
    - "chown -R non_root:non_root /home/non_root"
  script:
    # makepkg does not run as root, but it needs sudo to install dependencies
    - "cd /home/non_root && sudo -u non_root make package_arch"
    - "cd /home/non_root && pacman -U ArchLinux/*tar.zst --noconfirm"
    # artifacts must be relative to the working directory (/builds/leap/bitmask-vpn)
    - "cp /home/non_root/ArchLinux/*.tar.zst /builds/leap/bitmask-vpn"
  artifacts:
    paths:
      - '*.tar.zst'
    expire_in: 1 week
  tags:
    - linux
