---
stages:
  - lint
  - build
  - debian

build_test:
  image: registry.0xacab.org/jkito/bitmask-vpn:latest
  stage: build
  script:
    - make test
    - patch -p1 < docker/*.patch
    # TODO missing xcb package in the docker image. investigate what to install to run minimal tests.
    # - make test_ui
    - PROVIDER=bitmask && make vendor && make build
  tags:
    - linux
  artifacts:
    paths:
      - 'build/qt/release'
    expire_in: 1 week

lint:
  image: golangci/golangci-lint:v1.59-alpine
  stage: build
  script:
    - golangci-lint run --timeout=5m
  tags:
    - linux

debian:
  image: registry.0xacab.org/jkito/bitmask-vpn:latest
  stage: debian
  tags:
    - linux
  script:
    - 'PROVIDER="bitmask" make vendor && make package_deb'
  artifacts:
    paths:
      - 'deploy/*.deb'
    expire_in: 1 week

